import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SiteHeaderSection } from "./src/screens/LandingPage/sections/SiteHeaderSection/SiteHeaderSection";
import { SiteFooterSection } from "./src/screens/LandingPage/sections/SiteFooterSection/SiteFooterSection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Anima Project - Automatically generated by Anima",
  description: "Generated by Anima",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Anima Project - Automatically generated by Anima</title>
        <link rel="stylesheet" href="/tailwind.css" />
        <style
          dangerouslySetInnerHTML={{
            __html: `@import url("https://fonts.googleapis.com/css?family=Montserrat:500,800,italic|Plus+Jakarta+Sans:500,400,600|Inter:400");\n\n@font-face {\n    font-family: "Product Sans-Regular";\n    src: local("Product Sans-Regular");\n}\n@font-face {\n    font-family: "SF Compact Text-Medium";\n    src: local("SF Compact Text-Medium");\n}\n@font-face {\n    font-family: "SF Compact Display-Medium";\n    src: local("SF Compact Display-Medium");\n}`,
          }}
        />
        
      </head>
      <body className="min-h-full flex flex-col">
        <SiteHeaderSection />
          {children}
        <SiteFooterSection />
      </body>
    </html>
  );
}
